### ISSUE TITLE
Config file in dmd dir prevents host dmd from working

### ISSUE THREAD

**Issue by yebblies** [braddr/d-tester#40]
The autotester places a `sc.ini`/`dmd.conf` into dmd's source dir before building dmd, which overrides the host dmd's config file, causing the build to fail.

Possible solutions:
- Copy the config file _after_ dmd has been built.
- Add a switch to dmd to specify which config file to use?

**Comment by kiith-sa** [comment]
Similarly to #39, this is [blocking DDMD](http://forum.dlang.org/post/m8bt6s$1s86$1@digitalmars.com)

**Comment by MartinNowak** [comment]
See https://github.com/D-Programming-Language/dmd/pull/4256

**Comment by yebblies** [comment]
@braddr Could you please update the testers to make the host dmd's config file available in some way?  I can use make magic to get it from HOST_DC on posix but I can't see an easy way to do it with dm make .

**Comment by yebblies** [comment]
This works now.
