### ISSUE TITLE
history shows only checkout column

### ISSUE THREAD

**Issue by MartinNowak** [braddr/d-tester#42]
https://auto-tester.puremagic.com/platform-history.ghtml?projectid=1&os=Linux_64_64

![history](https://cloud.githubusercontent.com/assets/288976/5279722/2019f0e6-7ae8-11e4-9504-d07e45ab523b.png)

When I click on a single test all details are shown.

![single](https://cloud.githubusercontent.com/assets/288976/5279734/35e449f8-7ae8-11e4-9bc0-a800187877a0.png)

**Comment by braddr** [comment]
fixed
