### ISSUE TITLE
Defer merging to d-lang-bot, paying attention to pull labels for prioritization

### ISSUE THREAD

**Issue by wilzbach** [braddr/d-tester#52]
It would be very nice if the AutoTester could query the status of other CI providers before merging a PR.

See e.g. https://github.com/dlang/phobos/pull/4569

Ping @CyberShadow @JackStouffer

**Comment by braddr** [comment]
I've been waiting for github to implement merging based on status' for a while now.  They're so close to having all the pieces.  No one tester ought to be in charge of merging.  I'd love to rip that part out of my tester.

**Comment by JackStouffer** [comment]
> I've been waiting for github to implement merging based on status' for a while now.

Don't hold your breath :/

**Comment by braddr** [comment]
Actually, over the last year or so, they've been making some of the steps that lead in that direction.  I've never asked them, nor have I seen them say they're working on it, but it wouldn't shock me at all.

**Comment by MartinNowak** [comment]
We could easily move that functionality into dlang-bot (who already receives all github hooks), or wait for @CyberShadow's work on integrating test results.
Just let me know.

**Comment by wilzbach** [comment]
> We could easily move that functionality into dlang-bot (who already receives all github hooks), or wait for @CyberShadow's work on integrating test results.

I believe adding this functionality to the dlang-bot is the best way to go (as it can listen to all CI events and act accordingly), however I think we need to have more stable Travis builds than [currently](https://travis-ci.org/dlang/dmd/builds). I looked a bit at the build failures and it's mostly due to (a) build timeout (because we run all permutations and thus especially on the slower macOS machines it tends to timeout), (b) network errors (e.g. failure on git clone).
Maybe dlang-bot can comment on the PR if after X time the PR still hasn't merged or even better automatically restart the Travis build if it fails?

Another question is how dlang-bot would check that the PR is toggled for auto-merge, maybe a simple label (that thanks to the limited Github API only people with merge rights can add) will do?

**Comment by MartinNowak** [comment]
At dconf @CyberShadow was working on a fairly feature loaded integration for different CIs. Maybe that'll be the better approach.

> Another question is how dlang-bot would check that the PR is toggled for auto-merge, maybe a simple label (that thanks to the limited Github API only people with merge rights can add) will do?

Mmh, might be a valid approach.

**Comment by braddr** [comment]
I wrote the code to track label add/remove events last night and will transition it to production tonight.  Once I'm sure that's working, I'll add it to the queue prioritization code.  I'll leave the auto-merge functionality alone for now.  Doesn't hurt and can just be ignored.

Let me take a moment to rant about the github api... if an pull request is an issue, why are only a subset of the issue attributes returned?!  Sigh.  Labels are not part of what's included when you query for the list of open issues.  So, the background job I have that sync's with github doesn't see labels currently.  So if an event is missed, nothing is going to detect that and cleanup for now.  That code has bit rotten a bit over the years as the api has evolved, so it's over due for a good review and possibly rewrite anyway.

**Comment by wilzbach** [comment]
> I wrote the code to track label add/remove events last night and will transition it to production tonight. Once I'm sure that's working, I'll add it to the queue prioritization code.

Awesome. Thanks a lot!

> Let me take a moment to rant about the github api... if an pull request is an issue, why are only a subset of the issue attributes returned?! Sigh. 

Yeah it's poorly designed, but the new GraphQL API looks very promising.

> Labels are not part of what's included when you query for the list of open issues. So, the background job I have that sync's with github doesn't see labels currently. So if an event is missed, nothing is going to detect that and cleanup for now. 

Another gotcha that we discovered is that you can't use a logical or on queries for GH, but one can query the following to URLs to get a list of all PRs with "auto-merge" labels:

https://api.github.com/repos/dlang/phobos/issues?state=open&labels=auto-merge
https://api.github.com/repos/dlang/phobos/issues?state=open&labels=auto-merge-squash

or in Unix words:

```sh
(curl "https://api.github.com/repos/dlang/phobos/issues?state=open&labels=auto-merge" && curl "https://api.github.com/repos/dlang/phobos/issues?state=open&labels=auto-merge-squash") | jq '.[] | .number' | sort | uniq
```

**Comment by braddr** [comment]
nod.  I'm aware of the query.  What I'm more likely to switch to is pure state=open for both issues and pulls followed by detailed individual pull and issue queries for each object changed since the last time I've queried.  Lots of api hits, but about the only way to get the details.

**Comment by braddr** [comment]
Marking resolved.  The old system for auto-merging is in place still, but the prioritization based on tags is working correctly and has been for a while now.
