### ISSUE TITLE
Cancel pending/running builds on repush

### ISSUE THREAD

**Issue by MartinNowak** [braddr/d-tester#53]
I just debugged some CircleCI coverage testing, and created a huge amount of running jobs, by quickly repushing. Would make a lot of sense to save the resources and abort outdated test runs.
It looks a bit as if they already are canceled but only the job information isn't updated.

![triggered_builds](https://cloud.githubusercontent.com/assets/288976/17458784/b1f078fa-5c1e-11e6-95a5-dc731cb112d3.png)

**Comment by yebblies** [comment]
What do you mean?  They're all marked with A for aborted.

**Comment by MartinNowak** [comment]
If you click on them the clock is still incrementing, that lead me to believe they're still running.
