### ISSUE TITLE
Support squash commits 

### ISSUE THREAD

**Issue by wilzbach** [braddr/d-tester#55]
Imho for many PRs there we waste a lot of resources,  effort and time on letting the submitter squash the PR, ideally the auto-tester would be able to optionally squash all commits into one commit. I am not talking about the Github auto-squash feature (which I think would also be okay) but squashing the patch manually before merging it. 

See also this discussion on the mailing list: https://forum.dlang.org/post/ukcxzczovymwnumghywq@forum.dlang.org

CC @CyberShadow @JackStouffer @lodo1995 @ZombineDev

@braddr is this in theory possible to implement with the public code?

**Comment by lodo1995** [comment]
Yeah, it would be great if the person clicking the "toggle" button could specify to automagically squash all commits into one before merging. But I see two problems in this.
The first is that the squash should happen with the account of the person which does the PR, not the one who hits toggle (if I make a PR and Seb merges it, the squashed commit should have me as author, while the merge one should have Seb). This is also because this kind of squash is really happening inside the proposer's own fork, for which the person toggling automerge does not have write access.
The second is that the message of the squashed commit should be short and meaningful, so the only real solution is to let the person which decides to "squash and merge" to also decide the commit message.

**Comment by wilzbach** [comment]
> The first is that the squash should happen with the account of the person which does the PR, not the one who hits toggle (if I make a PR and Seb merges it, the squashed commit should have me as author, while the merge one should have Seb). This is also because this kind of squash is really happening inside the proposer's own fork, for which the person toggling automerge does not have write access.

This is absolutely no problem with git - we can rewrite the history locally as we want (and of course keep the ownership etc.). See e.g. this guide:

https://bocoup.com/weblog/git-workflow-walkthrough-merging-pull-requests

However I am not entirely sure how well this plays with the GitHub flow if we manually squash the commits, but I remember seeing this pattern being used before Github introduced the auto-squash feature. Another option would of course be to use their auto-squash feature but I remember @CyberShadow being a strong opponent of this.

> The second is that the message of the squashed commit should be short and meaningful, so the only real solution is to let the person which decides to "squash and merge" to also decide the commit message.

A simple solution would be to use the title of a PR (GitHub does the same), it's already editable by everyone with merge rights & part of the GitHub API  PR response.

> @braddr is this in theory possible to implement with the public code?

I answered my own question and found the bit where the Github Merge is triggered:

https://github.com/braddr/d-tester/blob/master/serverd/github_apis.d#L118

**Comment by braddr** [comment]
I strongly disagree with changing the set of commits at merge time.  The string of commits _is_ the pull.  The structure of it is an important part of what's being merged.  Agreeing on the individual pulls is much a part of the review as the final result.

**Comment by CyberShadow** [comment]
I'm still/also not a fan of the idea.

1. It creates more work (on the auto-tester, as well as in my lap for Digger and d-dot-git) for questionable gain.
2. The improvements this would bring don't seem to be considerable. Updating the PR in response to feedback and rebasing to fix merge conflicts is part of the ordeal, and rebasing to squish pointless commits is not different.
3. I worry that careless committers will use this to squash valuable history, when the commits are already sufficiently clean / self-contained.
4. When this is used to squash anything but small amendments, it hurts the precision of tools such as git-bisect.
5. Subjectively, I don't like the perversion of history :)

**Comment by wilzbach** [comment]
> I strongly disagree with changing the set of commits at merge time. 
> I'm still/also not a fan of the idea.

Fair enough, I will close this then.

There are just two things that we should bear in mind:

1) The main reason why I asked for squashing is because we loose a lot of time and resources with the back-and-forth pinging for a squash (especially with newcomers) - there are many examples, but this is a [recent one](https://github.com/dlang/phobos/pull/4740)

2)
> Agreeing on the individual pulls is much a part of the review as the final result.

This doesn't happen in all cases (probably because reviewers know that squashing is difficult for newcomers). My favorite example:
https://github.com/dlang/phobos/pull/4662
