### ISSUE TITLE
update host dmd to ~master.

### ISSUE THREAD

**Issue by UplinkCoder** [braddr/d-tester#56]
@braddr there is a bug in dmd prior to https://github.com/dlang/dmd/pull/6410/files#diff-0630e1297bdecef97aded9af2ddb879cL4041
which makes the newCTFE branch uncompilable.

**Comment by braddr** [comment]
The auto-testers will not be updated unless the project as a whole is accepting and prepared to lift the minimum supported version across the board.  The point of the version that it uses is that it's the official minimum base.  This doesn't change without care and consideration.  ie, bring it up with walter, andrei, and martin.

**Comment by braddr** [comment]
Resolving.  Re-open if/when the project leaders are asking for this change.
