### ISSUE TITLE
Trying to reach you about D bugzilla.

### ISSUE THREAD

**Issue by BBasile** [braddr/d-tester#57]
Hello, in D bugzilla:
- https://issues.dlang.org/enter_bug.cgi
- select __DMD__

component description includes a link to the old DIPs location. it needs to be updated.

**Comment by braddr** [comment]
Wrong forum for this, and either Walter or Andrei could have done this.  They can also setup additional bugzilla admins to could manage the configuration.

But, regardless, I made this edit.  Resolving.
