### ISSUE TITLE
FYI: DMD PR 2194 is stuck in the stable queue (it has been closed)

### ISSUE THREAD

**Issue by wilzbach** [braddr/d-tester#58]
https://auto-tester.puremagic.com/pull-history.ghtml?projectid=14&repoid=35&pullid=2194
https://auto-tester.puremagic.com/pulls.ghtml?projectid=14

**Comment by braddr** [comment]
A bit of bad data in the tester's mirror of the github pull data left over from an old bug prevented this one from being closed.   Manually closed the issue.  Should be (m)any of these left.
