### ISSUE TITLE
auto-tester is pending a lot these days

### ISSUE THREAD

**Issue by wilzbach** [braddr/d-tester#67]
![image](https://user-images.githubusercontent.com/4370550/35235585-e24cc3c0-ffa4-11e7-8f20-37d7b9016c52.png)

e.g. the linux 64_64 history just shows five builds within the last two days:

![image](https://user-images.githubusercontent.com/4370550/35235620-f619419e-ffa4-11e7-95c2-5865a111f40c.png)

https://auto-tester.puremagic.com/platform-history.ghtml?projectid=1&os=Linux_64_64

While there have been about ~10 PRs (not counting the force-pushes)

**Comment by braddr** [comment]
That image is the main branch builds.  It doesn't show any of the pull requests.  Click on the aptly named "Pull Requests" tab on the left to see those.

The build priority is:
1) prioritized pulls (aka, has been marked for auto-merge)
2) main branch builds
3) all other pulls

I'm 99% sure that what you're seeing is #1's taking priority over #2's.  If you can demonstrate that's not the case, then I'll be happy to dig deeper.  As to the last few days, you're not going to see more builds than there were merged pull requests, and this weekend was fairly slow.

**Comment by braddr** [comment]
reopen if evidence of a problem surfaces.
