### ISSUE TITLE
Missing triage info for "test phobos" stage?

### ISSUE THREAD

**Issue by marler8997** [braddr/d-tester#68]
Not sure if this is a problem with the phobos test code or the autotester, however, I have 2 different autotester runs from the same branch, one failed and one passed and I was unable to find any error messages to indicate what caused the failure.  Again, this could be a problem with the way the tests are reporting errors, or the autotester could be failing to propogate the error to the log, I'm not sure.  I've included the successful and failed runs to see if someone else may be able to confirm the issue and possibly determine if better error reporting could be implemented in either phobos or the autotester:

PASS: https://auto-tester.puremagic.com/show-run.ghtml?projectid=1&runid=3014376&dataid=21340243&isPull=true

FAIL: https://auto-tester.puremagic.com/show-run.ghtml?projectid=1&runid=3015138&isPull=true

**Comment by marler8997** [comment]
Actually, now that I've had a better look, I can see the regex unittest was killed:
```
make[1]: *** [generated/linux/release/32/unittest/std/regex/internal/tests.o] Killed
```
I don't see any messages that indicate why it was killed though...

**Comment by wilzbach** [comment]
Yes, I have reported this one here before and we even split std.regex because of it:  https://github.com/dlang/phobos/pull/6061

Looks like another split is required.

**Comment by braddr** [comment]
There's exactly two ways that I know of that tests can be killed, one by timeout and the other out of memory.  The auto-tester captures stderr and stdout of the entire build or test process.  There's not a lot else it can do.

**Comment by marler8997** [comment]
Looking at "https://github.com/braddr/at-client/blob/master/src/do_test_phobos.sh", it looks like all the autotester is doing is calling make...if we want to implement any post-test triage gathering, it probably needs to be done it phobos.
