### ISSUE TITLE
win32_64 on `stable` fails permanently

### ISSUE THREAD

**Issue by wilzbach** [braddr/d-tester#71]
```
The system cannot find the path specified.
failed to execute '\"Program Files (x86)"\"Microsoft Visual Studio 10.0"\VC\bin\amd64\cl.exe /c /nologo runnable\extra-files\cpp_abi_tests.cpp /Fotest_results\runnable\cpp_abi_tests.cpp.obj'
Makefile:220: recipe for target 'test_results/runnable/cpp_abi_tests.d.out' failed
gmake[1]: *** [test_results/runnable/cpp_abi_tests.d.out] Error 1
gmake[1]: *** Waiting for unfinished jobs....
```

I assume this is related to https://github.com/dlang/dmd/pull/7949
It happened persistently since yesterday:

https://auto-tester.puremagic.com/pulls.ghtml?projectid=14
https://auto-tester.puremagic.com/platform-history.ghtml?projectid=14&os=Win_32_64

![image](https://user-images.githubusercontent.com/4370550/36820593-e7e20478-1cee-11e8-8f60-4f9dbc62ce04.png)

(I wasn't sure whether you are aware of it)

**Comment by braddr** [comment]
Ok, and have you merged that change to stable?  It sure looks like not.

**Comment by wilzbach** [comment]
No, because I wasn't seeing no merge conflict on the log and your patch still applies?

https://github.com/braddr/at-client/blob/master/src/diff-dmd-win64.diff

... and any change in the area it affects would lead to merge conflicts, no?
(after all, that's why I want to push https://github.com/braddr/at-client/pull/8)

**Comment by wilzbach** [comment]
Hmm `stable` is still broken:

![image](https://user-images.githubusercontent.com/4370550/37275068-80313940-25de-11e8-91e8-5a2b06a9bbd3.png)

I tried to cherry-pick the PR with https://github.com/dlang/dmd/pull/8012, maybe that helps...

**Comment by wilzbach** [comment]
> I tried to cherry-pick the PR with dlang/dmd#8012, maybe that helps...

Nope, it doesn't:

https://auto-tester.puremagic.com/show-run.ghtml?projectid=14&runid=3071613&isPull=true

**Comment by wilzbach** [comment]
this is still happening:

https://auto-tester.puremagic.com/show-run.ghtml?projectid=1&runid=3098055&isPull=true

![image](https://user-images.githubusercontent.com/4370550/38133594-31a13ee8-3410-11e8-9a92-a1f5c71a5480.png)

**Comment by braddr** [comment]
Well, given that this pull moved files around, it's hardly shocking that it broke:  https://github.com/dlang/dmd/pull/8083

An incredibly minor change with a major negative.. good choices guys.

**Comment by marler8997** [comment]
Can we work as a team on this to make D better instead of using sarcasm to belittle others hard work?
